// <auto-generated />
using System;
using Assgiment1011.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assgiment1011.Data.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20230704062228_ChangeTypeOfStateInSQLTable")]
    partial class ChangeTypeOfStateInSQLTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Assgiment1011.Models.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(24)")
                        .HasDefaultValue("Active");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Annoucements", (string)null);
                });

            modelBuilder.Entity("Assgiment1011.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answer", (string)null);
                });

            modelBuilder.Entity("Assgiment1011.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Major")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Software Engineer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("AdditionalName");

                    b.HasKey("Id");

                    b.ToTable("Authors", (string)null);
                });

            modelBuilder.Entity("Assgiment1011.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(24)")
                        .HasDefaultValue("Word")
                        .HasColumnName("DocumentType");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("TopicId");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("Assgiment1011.Models.DocumentGallery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("DocumentGallries", (string)null);
                });

            modelBuilder.Entity("Assgiment1011.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BeginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("Assgiment1011.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ImageGalleryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ImageGalleryId");

                    b.ToTable("Images", (string)null);
                });

            modelBuilder.Entity("Assgiment1011.Models.ImageGallery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("ImageGalleries", (string)null);
                });

            modelBuilder.Entity("Assgiment1011.Models.Media.DocumentDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(24)")
                        .HasDefaultValue("Word");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .IsUnique();

                    b.ToTable("DocumentDetails", (string)null);
                });

            modelBuilder.Entity("Assgiment1011.Models.Media.ImageDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FormatType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(24)")
                        .HasDefaultValue("png")
                        .HasColumnName("ImageType");

                    b.Property<int>("ImageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImageId")
                        .IsUnique();

                    b.ToTable("ImageDetails", (string)null);
                });

            modelBuilder.Entity("Assgiment1011.Models.Media.VideoDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FormatType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(24)")
                        .HasDefaultValue("mp4")
                        .HasColumnName("VideoType");

                    b.Property<int>("VideoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VideoId")
                        .IsUnique();

                    b.ToTable("VideoDetails", (string)null);
                });

            modelBuilder.Entity("Assgiment1011.Models.New", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("News", (string)null);
                });

            modelBuilder.Entity("Assgiment1011.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("Assgiment1011.Models.TopicGallery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DocumentGalleryId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentGalleryId");

                    b.ToTable("TopicGalleries", (string)null);
                });

            modelBuilder.Entity("Assgiment1011.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Assgiment1011.Models.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VideoGalleryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("VideoGalleryId");

                    b.ToTable("Videos", (string)null);
                });

            modelBuilder.Entity("Assgiment1011.Models.VideoGallery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("VideoGalleries", (string)null);
                });

            modelBuilder.Entity("Assgiment1011.Models.Announcement", b =>
                {
                    b.HasOne("Assgiment1011.Models.Author", "Author")
                        .WithMany("Announcements")
                        .HasForeignKey("AuthorId")
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Assgiment1011.Models.Answer", b =>
                {
                    b.HasOne("Assgiment1011.Models.Author", "Author")
                        .WithMany("Answers")
                        .HasForeignKey("AuthorId")
                        .IsRequired()
                        .HasConstraintName("FKManyAnswerWithOneAuthor");

                    b.HasOne("Assgiment1011.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("FKOneQuestionHasManyAnswer");

                    b.Navigation("Author");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Assgiment1011.Models.Document", b =>
                {
                    b.HasOne("Assgiment1011.Models.Author", "Author")
                        .WithMany("Documents")
                        .HasForeignKey("AuthorId")
                        .IsRequired();

                    b.HasOne("Assgiment1011.Models.TopicGallery", "TopicGallery")
                        .WithMany("Documents")
                        .HasForeignKey("TopicId")
                        .IsRequired()
                        .HasConstraintName("FKManyDocumentWithOneTopicGallery");

                    b.Navigation("Author");

                    b.Navigation("TopicGallery");
                });

            modelBuilder.Entity("Assgiment1011.Models.DocumentGallery", b =>
                {
                    b.HasOne("Assgiment1011.Models.Author", "Author")
                        .WithMany("DocumentGalleries")
                        .HasForeignKey("AuthorId")
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Assgiment1011.Models.Event", b =>
                {
                    b.HasOne("Assgiment1011.Models.Author", "Author")
                        .WithMany("Events")
                        .HasForeignKey("AuthorId")
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Assgiment1011.Models.Image", b =>
                {
                    b.HasOne("Assgiment1011.Models.Author", "Author")
                        .WithMany("Images")
                        .HasForeignKey("AuthorId")
                        .IsRequired();

                    b.HasOne("Assgiment1011.Models.ImageGallery", "ImageGallery")
                        .WithMany("Images")
                        .HasForeignKey("ImageGalleryId")
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("ImageGallery");
                });

            modelBuilder.Entity("Assgiment1011.Models.ImageGallery", b =>
                {
                    b.HasOne("Assgiment1011.Models.Author", "Author")
                        .WithMany("ImageGalleries")
                        .HasForeignKey("AuthorId")
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Assgiment1011.Models.Media.DocumentDetail", b =>
                {
                    b.HasOne("Assgiment1011.Models.Document", "Document")
                        .WithOne("DocumentDetail")
                        .HasForeignKey("Assgiment1011.Models.Media.DocumentDetail", "DocumentId")
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Assgiment1011.Models.Media.ImageDetail", b =>
                {
                    b.HasOne("Assgiment1011.Models.Image", "Image")
                        .WithOne("ImageDetail")
                        .HasForeignKey("Assgiment1011.Models.Media.ImageDetail", "ImageId")
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("Assgiment1011.Models.Media.VideoDetail", b =>
                {
                    b.HasOne("Assgiment1011.Models.Video", "Video")
                        .WithOne("VideoDetail")
                        .HasForeignKey("Assgiment1011.Models.Media.VideoDetail", "VideoId")
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Assgiment1011.Models.New", b =>
                {
                    b.HasOne("Assgiment1011.Models.Author", "Author")
                        .WithMany("News")
                        .HasForeignKey("AuthorId")
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Assgiment1011.Models.Question", b =>
                {
                    b.HasOne("Assgiment1011.Models.Author", "Author")
                        .WithMany("Questions")
                        .HasForeignKey("AuthorId")
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Assgiment1011.Models.TopicGallery", b =>
                {
                    b.HasOne("Assgiment1011.Models.DocumentGallery", "DocumentGallery")
                        .WithMany("Topics")
                        .HasForeignKey("DocumentGalleryId")
                        .IsRequired();

                    b.Navigation("DocumentGallery");
                });

            modelBuilder.Entity("Assgiment1011.Models.User", b =>
                {
                    b.HasOne("Assgiment1011.Models.Author", "Author")
                        .WithOne("User")
                        .HasForeignKey("Assgiment1011.Models.User", "AuthorId")
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Assgiment1011.Models.Video", b =>
                {
                    b.HasOne("Assgiment1011.Models.Author", "Author")
                        .WithMany("Videos")
                        .HasForeignKey("AuthorId")
                        .IsRequired();

                    b.HasOne("Assgiment1011.Models.VideoGallery", null)
                        .WithMany("Videos")
                        .HasForeignKey("VideoGalleryId");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Assgiment1011.Models.VideoGallery", b =>
                {
                    b.HasOne("Assgiment1011.Models.Author", "Author")
                        .WithMany("VideoGalleries")
                        .HasForeignKey("AuthorId")
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Assgiment1011.Models.Author", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("Answers");

                    b.Navigation("DocumentGalleries");

                    b.Navigation("Documents");

                    b.Navigation("Events");

                    b.Navigation("ImageGalleries");

                    b.Navigation("Images");

                    b.Navigation("News");

                    b.Navigation("Questions");

                    b.Navigation("User")
                        .IsRequired();

                    b.Navigation("VideoGalleries");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("Assgiment1011.Models.Document", b =>
                {
                    b.Navigation("DocumentDetail")
                        .IsRequired();
                });

            modelBuilder.Entity("Assgiment1011.Models.DocumentGallery", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("Assgiment1011.Models.Image", b =>
                {
                    b.Navigation("ImageDetail")
                        .IsRequired();
                });

            modelBuilder.Entity("Assgiment1011.Models.ImageGallery", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Assgiment1011.Models.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Assgiment1011.Models.TopicGallery", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Assgiment1011.Models.Video", b =>
                {
                    b.Navigation("VideoDetail")
                        .IsRequired();
                });

            modelBuilder.Entity("Assgiment1011.Models.VideoGallery", b =>
                {
                    b.Navigation("Videos");
                });
#pragma warning restore 612, 618
        }
    }
}
